"""create initial database schema

Revision ID: e4d20bce5cd2
Revises: 
Create Date: 2026-07-01 18:02:24.408403+00:00
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'e4d20bce5cd2'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environment_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('map_name', sa.String(length=120), nullable=False),
    sa.Column('map_version', sa.String(length=40), nullable=False),
    sa.Column('agent_count', sa.Integer(), nullable=False),
    sa.Column('obstacle_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('shelf_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('delivery_zone_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_environment_configs_name_version')
    )
    op.create_index('ix_environment_configs_map_version', 'environment_configs', ['map_name', 'map_version'], unique=False)
    op.create_table('simulation_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('environment_config_id', sa.UUID(), nullable=True),
    sa.Column('run_name', sa.String(length=160), nullable=False),
    sa.Column('environment_name', sa.String(length=120), nullable=False),
    sa.Column('agent_count', sa.Integer(), nullable=False),
    sa.Column('map_version', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('created', 'running', 'completed', 'failed', 'cancelled', name='simulation_status'), server_default='created', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['environment_config_id'], ['environment_configs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_simulation_runs_environment_name', 'simulation_runs', ['environment_name'], unique=False)
    op.create_index('ix_simulation_runs_status_started_at', 'simulation_runs', ['status', 'started_at'], unique=False)
    op.create_table('agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('simulation_run_id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.String(length=120), nullable=False),
    sa.Column('agent_type', sa.String(length=80), server_default='warehouse_robot', nullable=False),
    sa.Column('policy_name', sa.String(length=120), nullable=True),
    sa.Column('spawn_position_x', sa.Float(), server_default='0', nullable=False),
    sa.Column('spawn_position_z', sa.Float(), server_default='0', nullable=False),
    sa.Column('status', sa.Enum('idle', 'active', 'delivering', 'charging', 'disabled', name='agent_status'), server_default='idle', nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('simulation_run_id', 'agent_name', name='uq_agents_run_agent_name')
    )
    op.create_index('ix_agents_run_status', 'agents', ['simulation_run_id', 'status'], unique=False)
    op.create_table('training_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('simulation_run_id', sa.UUID(), nullable=False),
    sa.Column('environment_config_id', sa.UUID(), nullable=True),
    sa.Column('algorithm', sa.String(length=60), server_default='ppo', nullable=False),
    sa.Column('max_steps', sa.Integer(), nullable=False),
    sa.Column('current_step', sa.Integer(), server_default='0', nullable=False),
    sa.Column('learning_rate', sa.Float(), nullable=False),
    sa.Column('batch_size', sa.Integer(), nullable=False),
    sa.Column('buffer_size', sa.Integer(), nullable=False),
    sa.Column('checkpoint_interval', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('created', 'running', 'paused', 'completed', 'failed', 'cancelled', name='training_status'), server_default='created', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['environment_config_id'], ['environment_configs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_training_sessions_algorithm', 'training_sessions', ['algorithm'], unique=False)
    op.create_index('ix_training_sessions_run_status', 'training_sessions', ['simulation_run_id', 'status'], unique=False)
    op.create_table('checkpoints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('training_session_id', sa.UUID(), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('reward_mean', sa.Float(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('collision_rate', sa.Float(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('storage_backend', sa.String(length=80), server_default='minio', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_best', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['training_session_id'], ['training_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('training_session_id', 'step', name='uq_checkpoints_session_step')
    )
    op.create_index('ix_checkpoints_is_best', 'checkpoints', ['is_best'], unique=False)
    op.create_index('ix_checkpoints_session_created_at', 'checkpoints', ['training_session_id', 'created_at'], unique=False)
    op.create_table('episodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('simulation_run_id', sa.UUID(), nullable=False),
    sa.Column('training_session_id', sa.UUID(), nullable=True),
    sa.Column('episode_number', sa.Integer(), nullable=False),
    sa.Column('reward_total', sa.Float(), server_default='0', nullable=False),
    sa.Column('step_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('success', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('collision_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('delivery_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['training_session_id'], ['training_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('simulation_run_id', 'episode_number', name='uq_episodes_run_episode_number')
    )
    op.create_index('ix_episodes_success', 'episodes', ['success'], unique=False)
    op.create_index('ix_episodes_training_session_number', 'episodes', ['training_session_id', 'episode_number'], unique=False)
    op.create_table('system_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('simulation_run_id', sa.UUID(), nullable=True),
    sa.Column('training_session_id', sa.UUID(), nullable=True),
    sa.Column('metric_name', sa.String(length=120), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('metric_unit', sa.String(length=40), nullable=True),
    sa.Column('source', sa.Enum('api', 'unity', 'training', 'system', 'llm', name='metric_source'), server_default='system', nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['training_session_id'], ['training_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_system_metrics_name_timestamp', 'system_metrics', ['metric_name', 'timestamp'], unique=False)
    op.create_index('ix_system_metrics_run_timestamp', 'system_metrics', ['simulation_run_id', 'timestamp'], unique=False)
    op.create_index('ix_system_metrics_source', 'system_metrics', ['source'], unique=False)
    op.create_index('ix_system_metrics_training_timestamp', 'system_metrics', ['training_session_id', 'timestamp'], unique=False)
    op.create_table('agent_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('simulation_run_id', sa.UUID(), nullable=False),
    sa.Column('episode_id', sa.UUID(), nullable=True),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('step', sa.Integer(), nullable=True),
    sa.Column('position_x', sa.Float(), nullable=False),
    sa.Column('position_z', sa.Float(), nullable=False),
    sa.Column('velocity', sa.Float(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=True),
    sa.Column('reward_delta', sa.Float(), server_default='0', nullable=False),
    sa.Column('event_type', sa.Enum('spawned', 'moved', 'pickup_started', 'pickup_completed', 'delivery_started', 'delivery_completed', 'reroute', 'collision_warning', 'collision', 'idle', 'custom', name='agent_event_type'), server_default='custom', nullable=False),
    sa.Column('reason_code', sa.String(length=120), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_events_agent_timestamp', 'agent_events', ['agent_id', 'timestamp'], unique=False)
    op.create_index('ix_agent_events_episode_step', 'agent_events', ['episode_id', 'step'], unique=False)
    op.create_index('ix_agent_events_event_type', 'agent_events', ['event_type'], unique=False)
    op.create_index('ix_agent_events_reason_code', 'agent_events', ['reason_code'], unique=False)
    op.create_index('ix_agent_events_run_timestamp', 'agent_events', ['simulation_run_id', 'timestamp'], unique=False)
    op.create_table('collisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('simulation_run_id', sa.UUID(), nullable=False),
    sa.Column('episode_id', sa.UUID(), nullable=True),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('other_agent_id', sa.UUID(), nullable=True),
    sa.Column('collision_type', sa.Enum('wall', 'obstacle', 'agent', 'shelf', 'unknown', name='collision_type'), server_default='unknown', nullable=False),
    sa.Column('position_x', sa.Float(), nullable=False),
    sa.Column('position_z', sa.Float(), nullable=False),
    sa.Column('impact_force', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['other_agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_collisions_agent_timestamp', 'collisions', ['agent_id', 'timestamp'], unique=False)
    op.create_index('ix_collisions_run_timestamp', 'collisions', ['simulation_run_id', 'timestamp'], unique=False)
    op.create_index('ix_collisions_type', 'collisions', ['collision_type'], unique=False)
    op.create_table('deliveries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('simulation_run_id', sa.UUID(), nullable=False),
    sa.Column('episode_id', sa.UUID(), nullable=True),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('pickup_location', sa.String(length=120), nullable=False),
    sa.Column('delivery_location', sa.String(length=120), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('success', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('reward', sa.Float(), server_default='0', nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_deliveries_agent_completed_at', 'deliveries', ['agent_id', 'completed_at'], unique=False)
    op.create_index('ix_deliveries_run_success', 'deliveries', ['simulation_run_id', 'success'], unique=False)
    op.create_table('model_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('training_session_id', sa.UUID(), nullable=False),
    sa.Column('checkpoint_id', sa.UUID(), nullable=True),
    sa.Column('model_name', sa.String(length=160), nullable=False),
    sa.Column('version', sa.String(length=80), nullable=False),
    sa.Column('algorithm', sa.String(length=60), server_default='ppo', nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('onnx_path', sa.String(length=500), nullable=True),
    sa.Column('reward_mean', sa.Float(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('collision_rate', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['checkpoint_id'], ['checkpoints.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['training_session_id'], ['training_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_name', 'version', name='uq_model_versions_name_version')
    )
    op.create_index('ix_model_versions_active', 'model_versions', ['is_active'], unique=False)
    op.create_index('ix_model_versions_training_session', 'model_versions', ['training_session_id'], unique=False)
    op.create_table('llm_explanations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_event_id', sa.UUID(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('model_name', sa.String(length=120), nullable=False),
    sa.Column('prompt_version', sa.String(length=80), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['agent_event_id'], ['agent_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_llm_explanations_event_created_at', 'llm_explanations', ['agent_event_id', 'created_at'], unique=False)
    op.create_index('ix_llm_explanations_model_name', 'llm_explanations', ['model_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_llm_explanations_model_name', table_name='llm_explanations')
    op.drop_index('ix_llm_explanations_event_created_at', table_name='llm_explanations')
    op.drop_table('llm_explanations')
    op.drop_index('ix_model_versions_training_session', table_name='model_versions')
    op.drop_index('ix_model_versions_active', table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_index('ix_deliveries_run_success', table_name='deliveries')
    op.drop_index('ix_deliveries_agent_completed_at', table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_index('ix_collisions_type', table_name='collisions')
    op.drop_index('ix_collisions_run_timestamp', table_name='collisions')
    op.drop_index('ix_collisions_agent_timestamp', table_name='collisions')
    op.drop_table('collisions')
    op.drop_index('ix_agent_events_run_timestamp', table_name='agent_events')
    op.drop_index('ix_agent_events_reason_code', table_name='agent_events')
    op.drop_index('ix_agent_events_event_type', table_name='agent_events')
    op.drop_index('ix_agent_events_episode_step', table_name='agent_events')
    op.drop_index('ix_agent_events_agent_timestamp', table_name='agent_events')
    op.drop_table('agent_events')
    op.drop_index('ix_system_metrics_training_timestamp', table_name='system_metrics')
    op.drop_index('ix_system_metrics_source', table_name='system_metrics')
    op.drop_index('ix_system_metrics_run_timestamp', table_name='system_metrics')
    op.drop_index('ix_system_metrics_name_timestamp', table_name='system_metrics')
    op.drop_table('system_metrics')
    op.drop_index('ix_episodes_training_session_number', table_name='episodes')
    op.drop_index('ix_episodes_success', table_name='episodes')
    op.drop_table('episodes')
    op.drop_index('ix_checkpoints_session_created_at', table_name='checkpoints')
    op.drop_index('ix_checkpoints_is_best', table_name='checkpoints')
    op.drop_table('checkpoints')
    op.drop_index('ix_training_sessions_run_status', table_name='training_sessions')
    op.drop_index('ix_training_sessions_algorithm', table_name='training_sessions')
    op.drop_table('training_sessions')
    op.drop_index('ix_agents_run_status', table_name='agents')
    op.drop_table('agents')
    op.drop_index('ix_simulation_runs_status_started_at', table_name='simulation_runs')
    op.drop_index('ix_simulation_runs_environment_name', table_name='simulation_runs')
    op.drop_table('simulation_runs')
    op.drop_index('ix_environment_configs_map_version', table_name='environment_configs')
    op.drop_table('environment_configs')
    # ### end Alembic commands ###
