[alembic]
script_location = alembic
prepend_sys_path = .
timezone = UTC
truncate_slug_length = 40
revision_environment = false
sourceless = false
version_locations = %(here)s/alembic/versions
output_encoding = utf-8

sqlalchemy.url = postgresql+psycopg://warehouse_user:warehouse_password@postgres:5432/warehouse_ai

[post_write_hooks]

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
